### ISSUE TITLE
action-cli-login@v2.0.0 login failures. 

### ISSUE THREAD

**Issue by pkskelly** [pnp/action-cli-login#18]
v2.0.0 of action-cli-login fails for password.

This issue seems similar to #8.  My initial attempt failed in a larger project so the information here is from attempts simplified to a simple project with only a single call to the cli login action in a yaml file using an M365 dev tenant admin account. 

ADMIN_USERNAME and ADMIN_PASSWORD properly configured in the repository secrets (see use of v1.0.0  below that confirms uid and pwd are correct). The logs for this run displays the following - note the url to the **organizations** endpoint.  The docs indicate this should default to the **common** endpoint. 

```
Run pnp/action-cli-login@v2.0.0
  with:
    ADMIN_USERNAME: ***
    ADMIN_PASSWORD: ***
ℹ️ Installing CLI for Microsoft 365...
✅ Completed installing CLI for Microsoft 365.
ℹ️ Logging in to the tenant...
/usr/local/bin/m365 login --authType password --userName *** -***
Error: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 400 | Attempted to reach: https://login.microsoftonline.com/organizations/oauth2/v2.0/token
Error: 🚨 Login to the tenant failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Error: The process '/usr/local/bin/m365' failed with exit code [1](https://github.com/pkskelly/CLI-Actions-Tests/runs/7155368642?check_suite_focus=true#step:2:1)
```

For a second attempt using v2.0.0 I specified an env variable in the workflow for CLIMICROSOFT365_TENANT env variable.  Using the guid for my dev tenant.  The log below was the same error, but at least the URL to the token endpoint was using the tenant id. 

```
/usr/local/bin/m365 login --authType password --userName *** -***
Error: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 400 | Attempted to reach: https://login.microsoftonline.com/d0b8659f-3125-4aa5-9fe6-7f00d66a7edc/oauth2/v2.0/token
Error: 🚨 Login to the tenant failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Error: The process '/usr/local/bin/m365' failed with exit code 1

```

I have tried a couple other combinations, but all fail.  Attempts from the CLI locally all work with the same credentials. 

However, if I change the action version to v1.0.0 then the login works fine (using the old ADAL,js per @waldekmastykarz  in #8).   The simplest call to only the v1.0.0 action with no env variable set, and only the uid and pwd from secrets returns the following successfully. 

```
Run pnp/action-cli-login@v1.0.0
  with:
    ADMIN_USERNAME: ***
    ADMIN_PASSWORD: ***
ℹ️ Installing Office 365 CLI...
✅ Completed installing Office 3[6](https://github.com/pkskelly/CLI-Actions-Tests/runs/7156316172?check_suite_focus=true#step:2:7)5 CLI.
ℹ️ Logging in to the tenant...
/usr/local/bin/o365 login --authType password --userName *** -***
/usr/local/bin/o365 status
connectedAs: ***
✅ Login successful.

```

Since this is not using federated identity, no MFA, etc. should v2.0.0 work?  Any thoughts on other options to try?

**Comment by garrytrinder** [comment]
Thanks for the report @pkskelly and apologies for the trouble.

Would it be possible for you to try 
`pnp/action-cli-login@v2.1.0`? Does this have the same issue?

**Comment by pkskelly** [comment]
Thanks for the quick response @garrytrinder!   

I ran the workflow again using v2.1.0 and the result is the same.  See log below. 

```
##[debug]Evaluating condition for step: 'Login to tenant'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Login to tenant
##[debug]Loading inputs
##[debug]Evaluating: secrets.ADMIN_USERNAME
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ADMIN_USERNAME'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: secrets.ADMIN_PASSWORD
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ADMIN_PASSWORD'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run pnp/action-cli-login@v2.1.0
ℹ️ Installing CLI for Microsoft [36](https://github.com/pkskelly/CLI-Actions-Tests/runs/7162473108?check_suite_focus=true#step:2:36)5...
✅ CLI for Microsoft 365 successfully installed at /usr/local/bin/m365
ℹ️ Attempting to log in...
/usr/local/bin/m365 login --authType password --userName *** -***
Error: network_error: Network request failed. Please check network trace to determine root cause. | Fetch client threw: Error: HTTP status code 400 | Attempted to reach: https://login.microsoftonline.com/organizations/oauth2/v2.0/token
Error: 🚨 The process '/usr/local/bin/m365' failed with exit code 1
Error: Error: The process '/usr/local/bin/m365' failed with exit code 1
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Login to tenant
```

Happy to try anything you can think of to help address. 

P.S: I love my new job, but man I miss frequent interactions community!!!

**Comment by martinlingstuyl** [comment]
Quite possibly this is related to https://github.com/pnp/cli-microsoft365/issues/3431

the issue is solved in the beta version 5.5. I think the cli action installs 5.4. 

You might check if you have special characters in your pw and change the password if you do.

**Comment by martinlingstuyl** [comment]
Or if you have influence on the version of the CLI that’s installed, you could try installing `@pnp/cli-microsoft365@next`

**Comment by pkskelly** [comment]
@martinlingstuyl - pwd certainly has special chars.  I can try that first.  If that does not resolve, I can look into trying to use v5.5.  Thanks!  I will not have a chance to get to this until tomorrow, but will update based on pwd change for sure.

**Comment by pkskelly** [comment]
Here are some of the attempts made and the results: 

1. v2.0.0 with new password (no "$" but still special chars): failed with same error message
2. v2.1.0 with new password (no "$" but still special chars): failed with same error message
3. Added a Action step prior login with v2.1.0 using "npm i -g @pnp/cli-microsoft365@next  --location=global" and using new pwd (no "$" but still special chars):  failed with same error message
4. Reset password again (only letters and numbers), using v2.1.0 and npm i -g @pnp/cli-microsoft365@next  --location=global  the action succeeded, logged in successfully. 
5. Removed call to install v5.5 of CLI with simpler pwd (only letters and numbers) and v2.1.0 : successfully logged in. 
6. Changed password to include single special char (Only letters and single '@') and v2.1.0 :  failed with same error message
7. Last attempt with v2.1.0. install of v5.5 of CLI, and simple pwd with single '@' : failed with same error message

Seems that even with the use of v5.5, special characters in a pwd are still an issue.

**Comment by pkskelly** [comment]
One last note, since the login Action main.ts installs the CLI, the installation of v5.5 in my earlier step is over-written.  Line 24 in main.ts installs the CLI and adding a step post login to echo the "m365 version" returns "v5.4.0".  If this is fixed in v5.5, I was not able to test properly since the action overwrote my install of @next for v5.5...  

Please let me know if you want me to try anything else.  At this point I am using a simpler password to continue my original efforts. Thanks for all the help.  Happy to try more if you want me to.

**Comment by martinlingstuyl** [comment]
No, this is OK, it’s clear the action is failing on the same issue. And you’re apparently correct that your installation is overwritten.

Unfortunately there is no option to specify the beta, so you’ll unfortunately have to wait with this till 5.5 is released. Or till we implemented a beta option here.

I don’t think all special chars are problematic, so you could try strengthening the password as much as you can.

**Comment by martinlingstuyl** [comment]
@michaelmaillot, would it make sense to allow users to specify that they want to use the `next` version when using this action?

**Comment by pkskelly** [comment]
Thanks @martinlingstuyl.   Feel free to close based on discussion.

**Comment by martinlingstuyl** [comment]
Will do 👍

**Comment by michaelmaillot** [comment]
Yes @martinlingstuyl definetely possible!

Thank you for raising this @pkskelly
